# Site settings
title: GeoBuzz - OpenGeo Suite Workshop
email: anton.bakker@geocat.net
email2: bartvde@boundless.com
logo1: img/boundless.png
logo2: img/geocat.png
url1: http://boundlessgeo.com
url2: https://www.geocat.net

license: "<a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/'><img alt='Creative Commons License' style='border-width:0' src='img/cc.png'></a>"
attribution: "Workshop material based on <a href='http://workshops.boundlessgeo.com/tutorial-censusmap/'>Building a Census Map</a>"
description: "A small adventure in map building with the OpenGeo Suite featuring GeoServer, PostGIS, OpenLayers 3 and het Nationaal Georegister"
baseurl: "/workshop-boundless-geocat"
url: "http://arbakker.github.io/workshop-boundless-geocat"

# Build settings
markdown: kramdown
permalink: pretty
